### ISSUE TITLE
세트에서 구성품을 쭉 출력해줄때!

### ISSUE THREAD

**Issue by shinwonse** [Jinho1011/Mount-app#52]
![스크린샷 2021-11-23 오후 12 53 53](https://user-images.githubusercontent.com/62709718/142969108-caa0827f-504e-4c8f-a1d3-fe2e5131718c.png)

지금은 임시로 저렇게 Items 컴포넌트를 복붙해놨는데요, map을 사용하면 될거같은데 잘 작성이 안되네요 혹시 도와주실수있나요!!

**Comment by Jinho1011** [comment]
`state.items` 가 item을 가지고 있는 배열이라고 한다면

```javascript
{state?.items.map((item) => {
    return <Items state={state} 
                       setState={setState} 
                       name={item.name} 
                       price={item.price} 
                       key={item.idx}
               />
}}
```

이렇게 하시면 될겁니다

**Comment by shinwonse** [comment]
잘 해결됐습니다 감사합니다!!
