### ISSUE TITLE
구성품의 개수 관리

### ISSUE THREAD

**Issue by shinwonse** [Jinho1011/Mount-app#54]
![화면 기록 2021-11-23 오후 4 26 53](https://user-images.githubusercontent.com/62709718/142985033-b5cc2a39-31ec-478d-a7a4-18d3c15f0d8c.gif)

구성품 개수를 현재 itemCnt라는 state로 관리중이었는데요 이렇게 하면 구성품 하나마다 state를 생성해줘야하는건지 아니면 다른 방법이 있을까요? 지금은 하나 누르면 다 올라가서요!

**Comment by amykim928** [comment]
저는 state 안에 여러 개를 넣어서
```javascript
const [state, setState] = useState({
    firstCheck: false,
    secondCheck: false,
  });
```
이런 식으로 한 다음에 state를 return했어요

**Comment by Jinho1011** [comment]
바뀐 코드 참고 바랍니다.
`/screens/Main/Detail/FoodSet/FoodSetContainer.js`, `/screens/Main/Detail/FoodSet/FoodSetPresenter.js`

**Comment by shinwonse** [comment]
확인했습니다 감사합니다 👍
