### ISSUE TITLE
route로 인자 넘기기 

### ISSUE THREAD

**Issue by shinwonse** [Jinho1011/Mount-app#60]
<img width="1250" alt="스크린샷 2021-12-02 오후 3 52 10" src="https://user-images.githubusercontent.com/62709718/144372584-107f6ad7-591c-420d-a428-128a41ae5ddf.png">

수량변경을 클릭했을 때 foodsetpresenter의 아이템들을 받아가야 하는데 방법을 잘 모르겠네요... route에 파라미터로 넘기는식으로 하나요?

**Comment by Jinho1011** [comment]
```javascript
           onPress={() => {
              navigation.navigate('FoodSetChangeCount', {id: item.id});
            }}>
```

이런식으로 parameter 넘기면 됩니다

**Comment by shinwonse** [comment]
그냥 저렇게 넘기는군요! 감사합니다!
