### ISSUE TITLE
음식세트에서 수량변경 넘어가는거

### ISSUE THREAD

**Issue by shinwonse** [Jinho1011/Mount-app#65]
![스크린샷 2021-12-06 오후 4 31 16](https://user-images.githubusercontent.com/62709718/144805350-d001e961-9a06-45d7-a4eb-58494a28703c.png)

인원수는 정상적으로 넘어오는데 아이템 수량은 안넘어오네요 그래서 억지로 저기 나와있는대로 useEffect에 수량 맞춰보려고했는데 네비게이트될때는 안되고 에뮬띄어두고 FoodSetCountChange 파일 공백썼다 지운다음에 다시 저장누르면 그상태에서 바로 에뮬에서 useEffect문이 실행됩니다. 아무래도 네비게이트될때는 새로 렌더링된걸로 처리가 안되는거같은데 어떻게 해결해야할지 계속 안되네요ㅜㅜㅜ

**Comment by leeyh-kor** [comment]
해결책이 될지는 모르겠지만, params가 외부에서 넘어오는 값이라면  State에 바로 할당 할 수 있습니다 . 
아무래도 네비게이트될때는 새로 렌더링된걸로 처리가 안되는거같은데 어떻게 해결해야할지 계속 안되네요ㅜㅜㅜ ==> 이부분은 useEffect의 두번째 인자로 route.params._state.items를 넣으면 해결 될 것 같습니다.

**Comment by shinwonse** [comment]
앗 운동다녀와서 답변을 이제 봤네요 감사합니다 해볼게요!!
